
exports.up = function(knex) {
  return knex.schema.createTable('professorUsers', users => {
        users.increments()
        users.string('username')
            .unique()
            .notNullable()
        users.string('password')
            .notNullable()
        users.string('email')
            .unique()
            .notNullable()
        users.string('firstName')
            .notNullable()
        users.string('lastName')
            .defaultTo('')
        users.string('type')
            .notNullable()
  })
  .createTable('studentUsers', users => {
        users.increments()
        users.string('username')
            .unique()
            .notNullable()
        users.string('password')
            .notNullable()
        users.string('email')
            .unique()
            .notNullable()
        users.string('firstName')
            .notNullable()
        users.string('lastName')
            .defaultTo('')
        users.string('type')
            .notNullable()
        users.integer('profId')
            .notNullable()
            .references('id')
            .inTable('professorUsers')
            .onUpdate('CASCADE')
            .onDelete('CASCADE')
  })

  .createTable('students', students => {
        students.increments()
        students.string('firstName')
            .notNullable()
        students.string('lastName')
            .notNullable()
  })
  .createTable('student list', sl => {
        sl.integer('profId')
            .references('id')
            .inTable('professorUsers')
            .onUpdate('CASCADE')
            .onDelete('CASCADE')
        sl.integer('studentId')
            .references('id')
            .inTable('students')
            .onUpdate('CASCADE')
            .onDelete('CASCADE')
  })
};

exports.down = function(knex) {
    return knex.schema
        .dropTableIfExists('student list')
        .dropTableIfExists('students')
        .dropTableIfExists('studentUsers')
        .dropTableIfExists('professorUsers')
};
